turbonomic operator 8.0

diff --git a/operator/helm-charts/base/kibana/templates/deployment.yaml b/operator/helm-charts/base/kibana/templates/deployment.yaml
--- a/operator/helm-charts/base/kibana/templates/deployment.yaml
+++ b/operator/helm-charts/base/kibana/templates/deployment.yaml
@@ -1,234 +1,156 @@
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
-  labels:
-    app: {{ template "kibana.name" . }}
-    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
-    heritage: {{ .Release.Service }}
-    release: {{ .Release.Name }}
   name: {{ template "kibana.fullname" . }}
-{{- if .Values.deployment.annotations }}
-  annotations:
-{{ toYaml .Values.deployment.annotations | indent 4 }}
-{{- end }}
+  labels: {{ include "kibana.labels" . | nindent 4 }}
 spec:
-  replicas: {{ .Values.replicaCount }}
-  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
+  replicas: {{ .Values.replicas }}
+  strategy:
+{{ toYaml .Values.updateStrategy | indent 4 }}
+  selector:
+    matchLabels:
+      app: {{ .Chart.Name }}
+      release: {{ .Release.Name | quote }}
   template:
     metadata:
-      annotations:
-        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
-{{- if .Values.podAnnotations }}
-{{ toYaml .Values.podAnnotations | indent 8 }}
-{{- end }}
       labels:
-        app: {{ template "kibana.name" . }}
-        release: "{{ .Release.Name }}"
-{{- if .Values.podLabels }}
-{{ toYaml .Values.podLabels | indent 8 }}
-{{- end }}
+        app: {{ .Chart.Name }}
+        release: {{ .Release.Name | quote }}
+        {{- range $key, $value := .Values.labels }}
+        {{ $key }}: {{ $value | quote }}
+        {{- end }}
+      annotations:
+        {{- range $key, $value := .Values.podAnnotations }}
+        {{ $key }}: {{ $value | quote }}
+        {{- end }}
+        {{/* This forces a restart if the configmap has changed */}}
+        {{- if .Values.kibanaConfig }}
+        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
+        {{- end }}
     spec:
-      serviceAccountName: {{ template "kibana.serviceAccountName" . }}
-      {{- if .Values.priorityClassName }}
-      priorityClassName: "{{ .Values.priorityClassName }}"
+{{- if .Values.priorityClassName }}
+      priorityClassName: {{ .Values.priorityClassName }}
+{{- end }}
+      securityContext:
+{{ toYaml .Values.podSecurityContext | indent 8 }}
+      {{- if .Values.serviceAccount }}
+      serviceAccount: {{ .Values.serviceAccount }}
       {{- end }}
-{{- if or (.Values.initContainers) (.Values.dashboardImport.enabled) (.Values.plugins.enabled) }}
+      volumes:
+        {{- range .Values.secretMounts }}
+        - name: {{ .name }}
+          secret:
+            secretName: {{ .secretName }}
+        {{- end }}
+        {{- if .Values.kibanaConfig }}
+        - name: kibanaconfig
+          configMap:
+            name: {{ template "kibana.fullname" . }}-config
+        {{- end }}
+    {{- with .Values.nodeSelector }}
+      nodeSelector:
+{{ toYaml . | indent 8 }}
+    {{- end }}
+    {{- with .Values.affinity }}
+      affinity:
+{{ toYaml . | indent 8 }}
+    {{- end }}
+    {{- with .Values.tolerations }}
+      tolerations:
+{{ toYaml . | indent 8 }}
+    {{- end }}
+    {{- if .Values.imagePullSecrets }}
+      imagePullSecrets:
+{{ toYaml .Values.imagePullSecrets | indent 8 }}
+    {{- end }}
+      {{- if .Values.extraInitContainers }}
+      # Currently some extra blocks accept strings
+      # to continue with backwards compatibility this is being kept
+      # whilst also allowing for yaml to be specified too.
       initContainers:
-{{- if .Values.initContainers }}
-{{- range $key, $value := .Values.initContainers }}
-      - name: "{{ $key }}"
-{{ toYaml $value | indent 8 }}
-{{- end }}
-{{- end }}
-{{- if .Values.dashboardImport.enabled }}
-      - name: {{ .Chart.Name }}-dashboardimport
-        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
-        command: ["/bin/bash"]
-        args:
-          - "-c"
-          - "/tmp/dashboardImport.sh"
-{{- if .Values.commandline.args }}
-{{ toYaml .Values.commandline.args | indent 10 }}
-{{- end }}
-        env:
-        {{- range $key, $value := .Values.env }}
-        - name: "{{ $key }}"
-          value: "{{ $value }}"
-        {{- end }}
-        volumeMounts:
-        - name: {{ template "kibana.fullname" . }}-dashboards
-          mountPath: "/kibanadashboards"
-        - name: {{ template "kibana.fullname" . }}-importscript
-          mountPath: "/tmp/dashboardImport.sh"
-          subPath: dashboardImport.sh
-        {{- range $configFile := (keys .Values.files) }}
-        - name: {{ template "kibana.name" $ }}
-          mountPath: "/usr/share/kibana/config/{{ $configFile }}"
-          subPath: {{ $configFile }}
-        {{- end }}
-{{- end }}
-{{- if .Values.plugins.enabled}}
-      - name: {{ .Chart.Name }}-plugins-install
-        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
-        command:
-          - /bin/bash
-          - "-c"
-          - |
-            set -e
-            rm -rf plugins/lost+found
-            plugins=(
-            {{- range .Values.plugins.values }}
-            {{ . }}
-            {{- end }}
-            )
-            if {{ .Values.plugins.reset }}
-            then
-              for p in $(./bin/kibana-plugin list | cut -d "@" -f1)
-              do
-                ./bin/kibana-plugin remove ${p}
-              done
-            fi
-            for i in "${plugins[@]}"
-            do
-              IFS=',' read -ra PLUGIN <<< "$i"
-              pluginInstalledCheck=$(./bin/kibana-plugin list | grep "${PLUGIN[0]}" | cut -d '@' -f1 || true)
-              pluginVersionCheck=$(./bin/kibana-plugin list | grep "${PLUGIN[0]}" | cut -d '@' -f2 || true)
-              if [ "${pluginInstalledCheck}" = "${PLUGIN[0]}" ]
-              then
-                if [ "${pluginVersionCheck}" != "${PLUGIN[1]}" ]
-                then
-                  ./bin/kibana-plugin remove "${PLUGIN[0]}"
-                  ./bin/kibana-plugin install "${PLUGIN[2]}"
-                fi
-              else
-                ./bin/kibana-plugin install "${PLUGIN[2]}"
-              fi
-            done
-        env:
-        {{- range $key, $value := .Values.env }}
-        - name: "{{ $key }}"
-          value: "{{ $value }}"
-        {{- end }}
-        volumeMounts:
-        - name: plugins
-          mountPath: /usr/share/kibana/plugins
-        {{- range $configFile := (keys .Values.files) }}
-        - name: {{ template "kibana.name" $ }}
-          mountPath: "/usr/share/kibana/config/{{ $configFile }}"
-          subPath: {{ $configFile }}
-        {{- end }}
-{{- if .Values.securityContext.enabled }}
-        securityContext:
-          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
-{{- end }}
-{{- end }}
-{{- end }}
+      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
+{{ tpl .Values.extraInitContainers . | indent 6 }}
+      {{- else }}
+{{ toYaml .Values.extraInitContainers | indent 6 }}
+      {{- end }}
+      {{- end }}
       containers:
-      - name: {{ .Chart.Name }}
-        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-        imagePullPolicy: {{ .Values.image.pullPolicy }}
-        {{- if .Values.commandline.args }}
-        args:
-          - "/bin/bash"
-          - "/usr/local/bin/kibana-docker"
-{{ toYaml .Values.commandline.args | indent 10 }}
-        {{- end }}
+      - name: kibana
+        securityContext:
+{{ toYaml .Values.securityContext | indent 10 }}
+        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
+        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
         env:
-        - name: ELASTICSEARCH_URL
-          value: "http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
-{{- if (not .Values.authProxyEnabled) }}
-        ports:
-        - containerPort: {{ .Values.service.internalPort }}
-          name: {{ template "kibana.name" . }}
-          protocol: TCP
+          {{- if .Values.elasticsearchURL }}
+          - name: ELASTICSEARCH_URL
+            value: "{{ .Values.elasticsearchURL }}"
+          {{- else if .Values.elasticsearchHosts }}
+          - name: ELASTICSEARCH_HOSTS
+            value: "{{ .Values.elasticsearchHosts }}"
+          {{- end }}
+          - name: SERVER_HOST
+            value: "{{ .Values.serverHost }}"
+{{- if .Values.extraEnvs }}
+{{ toYaml .Values.extraEnvs | indent 10 }}
 {{- end }}
-{{- if .Values.livenessProbe.enabled }}
-        livenessProbe:
-          httpGet:
-            path: {{ .Values.livenessProbe.path }}
-            port: {{ .Values.service.internalPort }}
-          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
-          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
+{{- if .Values.envFrom }}
+        envFrom:
+{{ toYaml .Values.envFrom | indent 10 }}
 {{- end }}
-{{- if .Values.readinessProbe.enabled }}
         readinessProbe:
-          httpGet:
-            path: {{ .Values.readinessProbe.path }}
-            port: {{ .Values.service.internalPort }}
-          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
-          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
-          successThreshold: {{ .Values.readinessProbe.successThreshold }}
-          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
+{{ toYaml .Values.readinessProbe | indent 10 }}
+          exec:
+            command:
+              - sh
+              - -c
+              - |
+                #!/usr/bin/env bash -e
+                http () {
+                    local path="${1}"
+                    set -- -XGET -s --fail -L
+
+                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
+                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
+                    fi
+
+                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
+                    if [[ "${STATUS}" -eq 200 ]]; then
+                      exit 0
+                    fi
+
+                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
+                    exit 1
+                }
+
+                http "{{ .Values.healthCheckPath }}"
+        ports:
+        - containerPort: {{ .Values.httpPort }}
+{{- if .Values.lifecycle }}
+        lifecycle:
+{{ toYaml .Values.lifecycle | indent 10 }}
 {{- end }}
         resources:
 {{ toYaml .Values.resources | indent 10 }}
         volumeMounts:
-        - name: {{ template "kibana.name" $ }}
-          mountPath: "/usr/share/kibana/config/kibana.yml"
-          subPath: "kibana.yml"
-{{- if .Values.extraVolumeMounts }}
-{{ toYaml .Values.extraVolumeMounts | indent 8 }}
-{{- end }}
-{{- if .Values.plugins.enabled}}
-        - name: plugins
-          mountPath: /usr/share/kibana/plugins
-{{- end }}
-{{- with .Values.extraContainers }}
-{{ tpl . $ | indent 6 }}
-{{- end }}
-{{- range .Values.extraConfigMapMounts }}
-        - name: {{ .name }}
-          mountPath: {{ .mountPath }}
-          subPath: {{ .subPath }}
-{{- end }}
-    {{- if .Values.image.pullSecrets }}
-      imagePullSecrets:
-{{ toYaml .Values.image.pullSecrets | indent 8 }}
-    {{- end }}
-    {{- if .Values.affinity }}
-      affinity:
-{{ toYaml .Values.affinity | indent 8 }}
-    {{- end }}
-    {{- if .Values.nodeSelector }}
-      nodeSelector:
-{{ toYaml .Values.nodeSelector | indent 8 }}
-    {{- end }}
-      tolerations:
-{{ toYaml .Values.tolerations | indent 8 }}
-{{- if .Values.securityContext.enabled }}
-      securityContext:
-        runAsUser: {{ .Values.securityContext.runAsUser }}
-        fsGroup: {{ .Values.securityContext.fsGroup }}
-{{- end }}
-      volumes:
-        - name: {{ template "kibana.name" . }}
-          configMap:
-            name: {{ template "kibana.fullname" . }}
-{{- if .Values.plugins.enabled}}
-        - name: plugins
-          {{- if .Values.persistentVolumeClaim.enabled }}
-          persistentVolumeClaim:
-            claimName: {{ template "kibana.fullname" . }}
-          {{- else }}
-          emptyDir: {}
+          {{- range .Values.secretMounts }}
+          - name: {{ .name }}
+            mountPath: {{ .path }}
+            {{- if .subPath }}
+            subPath: {{ .subPath }}
+            {{- end }}
           {{- end }}
-{{- end }}
-{{- if .Values.dashboardImport.enabled }}
-        - name: {{ template "kibana.fullname" . }}-dashboards
-          configMap:
-            name: {{ template "kibana.fullname" . }}-dashboards
-        - name: {{ template "kibana.fullname" . }}-importscript
-          configMap:
-            name: {{ template "kibana.fullname" . }}-importscript
-            defaultMode: 0777
-{{- end }}
-{{- range .Values.extraConfigMapMounts }}
-        - name: {{ .name }}
-          configMap:
-            name: {{ .configMap }}
-{{- end }}
-{{- if .Values.extraVolumes }}
-{{ toYaml .Values.extraVolumes | indent 8 }}
-{{- end }}
+          {{- range $path, $config := .Values.kibanaConfig }}
+          - name: kibanaconfig
+            mountPath: /usr/share/kibana/config/{{ $path }}
+            subPath: {{ $path }}
+          {{- end -}}
+      {{- if .Values.extraContainers }}
+      # Currently some extra blocks accept strings
+      # to continue with backwards compatibility this is being kept
+      # whilst also allowing for yaml to be specified too.
+      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
+{{ tpl .Values.extraContainers . | indent 6 }}
+      {{- else }}
+{{ toYaml .Values.extraContainers | indent 6 }}
+      {{- end }}
+      {{- end }}
